FROM node:20-alpine

WORKDIR /app

# Dá ao usuário node controle sobre /app
RUN chown -R node:node /app

# Copia os arquivos de dependências
COPY --chown=node:node package*.json ./

# A partir daqui trabalhamos como usuário node
USER node

RUN npm install

COPY --chown=node:node . .

EXPOSE 3000

ENV HOST=0.0.0.0
ENV PORT=3000

CMD ["npm", "start"]
